name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # todo: add 'nightly' to the matrix.
        #  Currently, it doesn't work because of this issue:
        #  https://github.com/neovim/neovim/issues/36015
        #  When it will be solved, we will be able to add it.
        #  nvim: [v0.11.4, nightly]
        nvim: [v0.11.4]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v6
      - name: Setup Neovim (${{ matrix.nvim }})
        uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.nvim }}
          neovim: true
      - name: Show Neovim version
        run: nvim --version
      - name: Run tests
        run: make test

